"""
Django settings for tethys project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import djcelery
import sys
from django.conf.global_settings import LOCALE_PATHS
from django.core.urlresolvers import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vz_w807nz!2$gb@b$3ew^ftm@uewy$nm#_rj-my16&^86%=*is'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'map.apps.MapConfig',
    'timeSeries.apps.TimeSeriesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'tethys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tethys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'adaptdb_data',
        'USER': 'django',
        'PASSWORD': 'Adapt-DBDJANGO',
        'HOST': '127.0.0.1',
        'PORT': '3306'
        }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-US'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = False
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# No internet connection support

#===============================================================================
# LOCAL_JAVASCIPT = ('<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>' + 
#                    '<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>')
#===============================================================================
LOCAL_JAVASCIPT = ('<script src="' + STATIC_URL + 'main/scripts/jquery.min.js"></script>' + 
                   '<script src="' + STATIC_URL + 'main/scripts/jquery-ui.min.js"></script>')

#===============================================================================
# LOCAL_MAP = '<script src="http://openlayers.org/en/v3.12.1/build/ol.js"></script>'
#===============================================================================
LOCAL_MAP = '<script src="' + STATIC_URL + 'map/scripts/ol.js"></script>'


# CELERY STUFF
BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"
CELERY_ROUTES = {'train': {'queue': 'train'},
                 'storeSatelliteData': {'queue': 'download'},
                 'updateSatelliteData': {'queue': 'download'}
                 }
djcelery.setup_loader()

# LOGIN
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('main:header')

# OpenCL
if sys.platform=='linux':
    # OPENCL
    OPENCL_PLATFORM = 0
    OPENCL_DEVICE = 'CPU'
    
    # SATELLITE DATA
    home = os.path.expanduser("~")
    SATELLITE_DOWNLOAD = os.path.join(home, 'Tethys Data/satellite download')
    SATELLITE_STORE = os.path.join(home, 'Tethys Data/satellite store')
else:
    # OPENCL
    OPENCL_PLATFORM = 0
    OPENCL_DEVICE = 'GPU'
    
    # SATELLITE DATA
    SATELLITE_DOWNLOAD = 'X:\satellite download'
    SATELLITE_STORE = 'X:\satellite store'

# debug
DEBUG = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
MAX_UPLOAD_SIZE = 104857600